export const motdList = [
  "The brewery has that familiar warmth today.",
  "Ready to get the vessels moving again.",
  "Let’s brew something that brings people joy.",
  "Your batches have been waiting for you.",
  "Time to wake the yeast gently.",
  "Your vessels stand ready in the evening light.",
  "You know the routine — let’s brew.",
  "The brewhouse feels alive when you arrive.",
  "It’s a good day for mead.",
  "Let’s brew something that tastes like summer.",
  "Craft with intention.",
  "You’re back — quality follows.",
  "Ready for a bit of brewing magic.",
  "Your vessels have been patient.",
  "Let’s give the yeast something to work with.",
  "The brewery feels better when you’re here.",
  "You brew with confidence.",
  "The brewhouse stirs when you walk in.",
  "Let’s brew something with a sense of adventure.",
  "Your batches have missed your attention.",
  "You’re back — things can move forward.",
  "Your vessels are ready for the next chapter.",
  "Let’s brew something that makes people pause.",
  "The brewery is in steady hands now.",
  "You brew with skill.",
  "Let’s brew something that warms the spirit.",
  "Brew with pride.",
  "You’re back — the yeast will appreciate it.",
  "Your vessels are ready for work.",
  "Let’s brew something bright and refreshing.",
  "The brewery acknowledges your return.",
  "You’re back — quality is expected.",
  "Let’s brew something that brings energy.",
  "Brew with intention.",
  "Your vessels are ready for new steps.",
  "You’re back — good momentum ahead.",
  "Let’s brew something that feels free.",
  "The brewhouse wakes up with you.",
  "You brew with experience.",
  "Let’s brew something that feels joyful.",
  "Your vessels are ready for action.",
  "You’re back — time to focus.",
  "Let’s brew something that feels like rain in summer.",
  "The brewery settles when you walk in.",
  "You brew with mastery.",
  "Let’s brew something that feels dreamlike.",
  "Your vessels are always ready for you.",
  "You’re back — time for a little magic.",
  "Let’s brew something that feels victorious.",
  "The brewery has missed your presence.",
  "You’re back — craftsmanship follows.",
  "Let’s brew something that feels like sunset.",
  "Your vessels warm up when you arrive.",
  "You brew with true craftsmanship.",
  "Let’s brew something peaceful.",
  "The brewery feels quiet without you.",
  "You’re back — time to bring life to the batches.",
  "Let’s brew something that feels like spring.",
  "Your vessels are ready for careful hands.",
  "You brew with certainty.",
  "Let’s brew something that feels like mountain air.",
  "The brewery opens itself when you walk in.",
  "You’re back — craftsmanship rises.",
  "Let’s brew something warm and familiar.",
  "Your vessels are ready for a new story.",
  "You brew with heritage.",
  "Let’s brew something joyful.",
  "The brewery improves when you log in.",
  "You’re back — real quality begins.",
  "Let’s brew something inspired by the northern lights.",
  "Your vessels are ready for subtle magic.",
  "You brew with love for the craft.",
  "Let’s brew something shaped by ocean wind.",
  "The brewery stands proud today.",
  "You’re back — momentum returns.",
  "Let’s brew something autumn‑soft.",
  "Your vessels are ready for another round.",
  "You brew with brewing in your bones.",
  "Let’s brew something winter‑warm.",
  "The brewery brightens when you walk in.",
  "You’re back — time for real craft.",
  "Let’s brew something touched by spring light.",
  "Your vessels are ready again.",
  "You brew with persistence.",
  "Let’s brew something that carries good energy.",
  "The brewery feels content when you’re here.",
  "You’re back — time for quality work.",
  "Let’s brew something inspired.",
  "Your vessels are ready for your guidance.",
  "You brew with purpose.",
  "Let’s brew something shaped by true craftsmanship.",
  "The brewery feels awake with you here.",
  "You’re back — brewing rises to a higher level.",
  "Let’s brew something adventurous in a glass.",
  "Your vessels are ready to shine.",
  "You brew with natural instinct.",
  "Let’s brew something genuinely happy.",
  "The brewery feels complete when you arrive."
];


export function getNextMotd() {
  const index = Math.floor(Math.random() * motdList.length);
  return motdList[index];
}
