export const motdList = [
  "The brewery has that familiar warmth today.",
  "Ready to get the vessels moving again.",
  "Let’s brew something that brings people joy.",
  "Batches have been sitting steady since last check.",
  "Time to wake the yeast gently.",
  "The vessels stand ready in the evening light.",
  "You know the routine — let’s brew.",
  "The brewhouse feels alive when work begins.",
  "It’s a good day for mead.",
  "Let’s brew something that tastes like summer.",
  "Craft with intention.",
  "Quality follows good workflow.",
  "Ready for a bit of brewing magic.",
  "The vessels have been patient.",
  "Let’s give the yeast something to work with.",
  "The brewery feels better when it’s in use.",
  "You brew with confidence.",
  "The brewhouse stirs when the lights come on.",
  "Let’s brew something with a sense of adventure.",
  "Batches appreciate steady attention.",
  "Momentum is ready to move forward.",
  "The vessels are ready for the next chapter.",
  "Let’s brew something that makes people pause.",
  "The brewery is in steady hands.",
  "You brew with skill.",
  "Let’s brew something that warms the spirit.",
  "Brew with pride.",
  "The yeast will appreciate consistency.",
  "The vessels are ready for work.",
  "Let’s brew something bright and refreshing.",
  "The brewery settles into rhythm.",
  "Quality is expected here.",
  "Let’s brew something that brings energy.",
  "Brew with intention.",
  "The vessels are ready for new steps.",
  "Good momentum ahead.",
  "Let’s brew something that feels free.",
  "The brewhouse wakes up with activity.",
  "You brew with experience.",
  "Let’s brew something joyful.",
  "The vessels are ready for action.",
  "Time to focus on the craft.",
  "Let’s brew something that feels like rain in summer.",
  "The brewery settles when work begins.",
  "You brew with mastery.",
  "Let’s brew something dreamlike.",
  "The vessels are always ready for another batch.",
  "Time for a little magic.",
  "Let’s brew something victorious.",
  "The brewery has missed movement.",
  "Craftsmanship follows steady hands.",
  "Let’s brew something that feels like sunset.",
  "The vessels warm up once work starts.",
  "You brew with true craftsmanship.",
  "Let’s brew something peaceful.",
  "The brewery feels quiet between sessions.",
  "Time to bring life to the batches.",
  "Let’s brew something that feels like spring.",
  "The vessels are ready for careful hands.",
  "You brew with certainty.",
  "Let’s brew something that feels like mountain air.",
  "The brewery opens itself when work begins.",
  "Craftsmanship rises with consistency.",
  "Let’s brew something warm and familiar.",
  "The vessels are ready for a new story.",
  "You brew with heritage.",
  "Let’s brew something joyful.",
  "The brewery improves with steady workflow.",
  "Real quality begins with preparation.",
  "Let’s brew something inspired by northern lights.",
  "The vessels are ready for subtle magic.",
  "You brew with love for the craft.",
  "Let’s brew something shaped by ocean wind.",
  "The brewery stands proud today.",
  "Momentum returns with active brewing.",
  "Let’s brew something autumn‑soft.",
  "The vessels are ready for another round.",
  "You brew with brewing in your bones.",
  "Let’s brew something winter‑warm.",
  "The brewery brightens when work begins.",
  "Time for real craft.",
  "Let’s brew something touched by spring light.",
  "The vessels are ready again.",
  "You brew with persistence.",
  "Let’s brew something that carries good energy.",
  "The brewery feels content during steady work.",
  "Time for quality craft.",
  "Let’s brew something inspired.",
  "The vessels are ready for guidance.",
  "You brew with purpose.",
  "Let’s brew something shaped by true craftsmanship.",
  "The brewery feels awake during active brewing.",
  "Brewing rises to a higher level with focus.",
  "Let’s brew something adventurous in a glass.",
  "The vessels are ready to shine.",
  "You brew with natural instinct.",
  "Let’s brew something genuinely happy.",
  "The brewery feels complete when the craft is underway."
];

export function getNextMotd() {
  const index = Math.floor(Math.random() * motdList.length);
  return motdList[index];
}
