export default `

This is a crash course in Malt Extract and Beer Kits

What is Malt Extract?
Malt extract is the concentrated and/or dried sugars extracted from malted barley. Most of the malt extract produced in the world is used in various food products: everything from malted milk, to breakfast cereals, to baking additives, to pet foods. There are two main grades of barley: malting grade and feed grade. There are also several sub-classes within these grades.  The barley that is used to make food extracts is a lower grade of malting barley, such as C and D grades, and distiller’s grade. These lower grade malting barleys are typically smaller kernels with higher protein levels, less convertible starch, and a higher proportion of husk material by weight. The barley that is used for brewing beer is universally the highest grade, and to brew the best possible beer you need to be sure you are using extract made from brewing grade barley.
The malting process consists of soaking and draining the barley to initiate the germination of the plant from the seed. When the seed germinates, it activates enzymes that start converting its starch reserves and proteins into sugars and amino acids that the growing plant can use. The purpose of malting is to release these enzymes and starch reserves for use by the brewer. Once the seeds start to sprout, the grain is dried in a kiln to stop the enzymes until the brewer is ready to use the grain, which is generically referred to as malt. There are many specific types of malt that yield a wide range of flavors and aromas and are used to make different styles of beer. These include lager malts, pale malts, Vienna malts, Munich malts, toasted, roasted, and chocolate malts.

Malt extract starts out in the brewhouse just the same as if you were brewing a beer. The brewer crushes the malted barley and soaks it in hot water to reactivate and accelerate the enzyme activity, converting the barley’s starch reserves into a fermentable sugar solution called wort. To make beer, the wort is boiled with hops and fermented with yeast. To make malt extract, the wort is transferred to evaporators after boiling instead of to a fermentor. Malt extract is simply concentrated wort. The malt extract may consist of a single malt or a combination of different types, depending on what style of beer is being made. 
Brewers boil the wort to accomplish two things: to coagulate the hot break proteins that otherwise contribute to haze and long-term flavor stability problems, and to isomerize the hop alpha acids for bitterness. Manufacturers of malt extract for brewing do the same steps for the same reasons, although a lot of malt extract is made unhopped. Those extracts are only boiled long enough to coagulate the proteins. The wort is then run into vacuum chambers for dehydration to make a shelf-stable product, at 80% solids, without the use of preservatives. By boiling off the water under a partial vacuum, the wort sugars are not caramelized by the full heat of boiling and the original flavor and color of the wort is preserved. To make a hopped extract, hops can be added to the initial boil or hop iso-alpha acid extracts can be added to the extract later. Malt extract takes a lot of the work out of homebrewing. 
Malt extract is sold in both liquid (syrup) and powdered forms. The syrups are approximately 20 percent water, so 4 pounds of dry malt extract (DME) is roughly equal to 5 pounds of liquid malt extract (LME). Dry malt extract is produced by heating and spraying the liquid extract from an atomizer in a tall heated chamber. The small droplets dry and cool rapidly as they settle to the floor. DME is identical to LME except for the additional dehydration to about 2% moisture. DME is typically not hopped. 

What is Malt Sugar? 
Brewing beer is all about working with sugars—glucose, fructose, sucrose, maltose, and all the rest. If you are like me, you want someone to explain it without getting too technical. Bear with me, as I need to lay some groundwork and describe the different building blocks. It won’t take long and once you understand what everything’s made of, it becomes a lot easier to understand the answers. 

Sugars (technical name: saccharides) are made up of groups of 1 to 9 carbon atoms. The common sugars like glucose and sucrose are made of groups of 6 carbon atoms and are therefore called “hexoses.” A mono-saccharide is single sugar group, a di-saccharide is composed of two sugar groups, a tri-saccharide is three, et cetera. The most common type of sugar is the monosaccharide “glucose” (aka. dextrose, blood sugar, corn sugar). Other monosaccharides relevant to brewing are fructose and galactose. Compositionally, these are all the same, but they are isomers of each other i.e., their chemical structure/arrangement gives them different properties. For instance, fructose (also known as fruit sugar) is an isomer of glucose, but tastes sweeter than glucose. 

Table 5 lists the approximate levels of the different sugars found in a typical beer wort. The main constituent is maltose, followed by assorted dextrins, maltotriose, glucose, sucrose and fructose. Maltose is a glucose disaccharide, which means that it is made up of two glucose molecules. Maltotriose is a trisaccharide consisting of three glucose molecules. Sucrose (commonly known as table sugar) is a disaccharide that is made of one glucose and one fructose, and occurs naturally in plants. Sources include sugar cane, beets, maple sap, and nectar. Dextrins (aka. oligosaccharides) are larger sugars consisting of more than three monosaccharide groups. In general, monosaccharides are sweeter tasting than (poly)saccharides. In descending order of sweetness: fructose is sweeter than sucrose, which is sweeter than glucose, which is sweeter than maltose, which is sweeter than maltotriose. (Not that it matters in fermentation; I just thought you would like to know.) The different types of common sugars and their use in brewing will be discussed in more detail Section IV—Recipes, Experimentation, and Troubleshooting.
Fermentation of Sugars
Yeast are apparently very methodical creatures. Even though sucrose is usually a small percentage of the wort, studies have shown that most brewing yeast strains seem to work on it first – breaking it down into its glucose and fructose components. Once the sucrose has been broken down, the yeast cells consume the glucose first, followed by fructose, maltose, and finally maltotriose. Some yeast strains behave differently; eating maltose in parallel with the monosaccharides, but that would seem to be the exception. In addition, most strains are glucophilic, utilizing most of the glucose in the wort before consuming the other monosaccharides, and fermenting most of those before fermenting maltose, and subsequently maltotriose. In fact, it is known that high levels of glucose and fructose in a wort (e.g. >15-20%) will inhibit the fermentation of maltose. This repressive behavior is probably a common cause of stuck fermentations in worts containing a lot of refined sugars— the yeast have fermented the monosaccharides and then quit, leaving more than half of the total sugars unfermented.

Yeast metabolize the different wort sugars in different ways. To consume the disaccharide sucrose, the yeast utilize an enzyme called invertase, which works outside the cell to separate the molecule into its components— glucose and fructose. The glucose and fructose are then transported through the cell wall and metabolized inside the cell. Conversely, maltose and maltotriose are transported into the cell first, and then are broken down into glucoses by the enzyme maltase. Even though the enzyme for both sugars is the same, maltose is typically consumed first, indicating that the cell wall transport mechanism for the two sugars is different. Maybe maltotriose is too big to get through the maltose door!

The take-home message is that all fermentable sugars are broken down into monosaccharides like glucose before being utilized by the yeast, and that yeast evidently prefer to eat their sugars one course at a time. This has big implications for choosing our malt extract and formulating recipes.

Shopping for Malt Extract
The freshness of the extract is important, particularly for the syrup. Liquid malt extract typically has a shelf life of about 2 years, depending on storage conditions, during which time its color will approximately double. The Maillard reactions that are responsible for the color change can generate off-flavors like licorice, molasses, and ballpoint pen aroma. Beer brewed with old extract syrup can also have a blunt, stale, or soapy flavor to it. These flavors are caused by the oxidation of the fatty acid compounds in the malt. These off-flavors are part of a group that is collectively known as extract twang. Homebrewers will often complain that they can’t make good beer with extract, but it’s just a matter of freshness. The bottom line is to use fresh extract by checking the “Use By” dates on the cans or to buy from a shop that has a high stock turnover. Dry malt extract has a better shelf life than the liquid because the extra de-hydration slows the chemical reactions. If you can’t get fresh liquid extract, use the dry.

Another quality of an extract that can have a particularly strong affect on the quality of the finished beer is Free Amino Nitrogen (FAN). FAN is a measure of the amount of amino acid nitrogen that is available to the yeast for nutrition during fermentation. Without sufficient FAN, the yeast are less efficient and produce more fermentation byproducts which result in off-flavors in the beer. This is why it is important to not add sugar to the wort like most canned kit instruction say to; use more malt extract instead. Corn, rice, and cane sugar don’t contain FAN. Adding large percentages of these adjuncts to the wort dilutes the FAN and deprives the yeast of the nutrients they need to grow and function. Yeast nutrient containing FAN can be added to the wort if necessary. See Chapter 6 for more information.

Malt extract is available as either hopped or unhopped. Hopped extracts are boiled with hops prior to dehydration and usually contain a mild to moderate level of bitterness. Alexander’s, Briess, Coopers, Edme, Ireks, John Bull, Mountmellick, Muntons, Northwestern, and Weyermanns are all high quality brands. See Figure 29 for an array of various malt extract products.

Malt extract is commonly available in pale, amber, and dark varieties, and can be mixed depending on the style of beer desired. Wheat malt extract is also available and new extracts tailored to specific beer styles are arriving all the time. The quality of extracts and beer kits has improved greatly in the last 5 years. An all-extract brewer will be quite satisfied brewing entirely from beer kits as long as they ignore the instructions on the can and follow the guidelines in this book. With the variety of extract now available, there are few beer styles that cannot be brewed using extract alone. For more information on using extract to make different styles of beer, see chapters 13 and 20.
Choosing a Good Kit
Figure 30 – Building your own kit for Cincinnati Pale Ale.
What is a beer kit? A typical beer kit consists of a yeast packet and one can of hopped malt extract that is designed to be diluted, pasteurized, and fermented into a reasonable example of a particular style of beer. Often the malt extract in the single can kits is brewed to a relatively low fermentability and are extended with highly fermentable adjuncts like corn or cane sugar. This type of kit is often referred to as “kit and kilo” brewing because the instructions usually say to add 1 kilogram (~2 lbs.) of sugar to the extract before fermenting. These kits make an acceptable beer, but usually don’t taste just like the commercial example the homebrewer had hoped to make. And let’s be frank about this – commercial beers are not brewed from a dextrinous concentrate and highly refined sugars in small batches at the mercy of the household environment. So, it’s no wonder that these homebrewed kits don’t taste exactly the same as the real thing. If you have purchased one of these kits, I recommend that you use pale malt extract in place of the sugar, and use fresh yeast. You will be much happier with the results.
 
But there are also better kits on the market that will taste more like the commercial beer that you are trying to copy. These all-malt kits consist of two cans of malt extract and are not meant to be extended with sugar. These all-malt kits will produce a very good beer that taste more like what you’d expect. There are also no-boil liquid wort kits that are simply diluted in the fermentor, and these make very good beer too. There has been a revolution in home beer making over the past decade and beer kit manufacturers have responded by creating more interesting kits that can produce outstanding beers. I have talked with most of the top manufacturers in the past couple years as I worked on this revision, and every time I was impressed by their passion for beer and their pride in their products.

In addition to the name brand beer kits available, many of the better homebrew shops package their own kits and provide more comprehensive instructions. Kits assembled by homebrewers for homebrewers are probably the best way to get started. If your supply shop does not offer this type of kit, you can assemble your own. Cincinnati Pale Ale (see sidebar) is a basic American pale ale and quite tasty. You will be amazed at the full body and rich taste compared to most commercial beers. More recipes and style guidelines are given in Chapter 20. You can use any one of those recipes for your first batch by choosing the all-extract option, or you can read Section II—Brewing with Extract and Specialty Grain, and try that easy additional step for a bit more liveliness in your first batch.
How Much Extract to Use
A rule of thumb is one pound of liquid extract per gallon of water for a light bodied beer. One and a half pounds per gallon produces a richer, full bodied beer. A pound of LME typically yields a gravity of 1.034–38, as measured by a hydrometer, when dissolved in water to make one gallon of wort. DME yields about 1.040–43. These yield values are often referred to as Points per Pound per Gallon. If someone tells you that a certain extract or malt’s yield is 36 points, it means that when 1 pound is dissolved in water to make 1 US gallon of wort, the gravity is 1.036. If that 1 pound is dissolved in water to make 3 US gallons, its gravity would be 36/3 = 12 or 1.012. The gravity is how the strength of a beer is described. Most commercial beers have an Original Gravity (OG) of 1.035–1.050. (3.2-4.5% ABV)

Gravity (OG) Calculations
Total gravity points = an extract’s yield x mass 
= specific gravity x total volume. 
If you want to brew 5 gallons of 1.040 gravity beer, this would call for:
5 lbs of DME having 40 pts/lb./gal, or 5.5 lbs of LME having 36 pts/lb./gal.
40 pts/gal x 5 gal = 200 pts total
200 pts = 36 pts/lb. x (?) lbs  
=> (?) lbs = 200 / 36 = 5.55 lbs. 
5.55 lb. of 36 pts/lb./gal LME are needed to make the same 5 gallons of beer. 

This concept also works for liters and kilograms. Points per pound per gallon translates to points per kilogram per liter (PKL), or algebraically, liter degrees per kilogram. The conversion factor is 1 PPG = 8.3454 PKL.

Gravity vs. Fermentability
Different extracts have different degrees of fermentability. In general, the darker the extract, the more complex sugars it will contain and the less fermentable it will be. Amber extract will typically have a higher finishing gravity than pale extract and dark will be higher than amber. This is not always the case, though. By manipulating the mash conditions, the relative percentages of sugars that are extracted from the mash can be varied. A brewer can produce a wort that is almost entirely made up of highly fermentable sugars like maltose or he can produce one that has a higher percentage of unfermentable complex carbohydrates. Because these complex sugars are not very fermentable, the beer will have a higher finishing gravity. While most of the perception of a beer’s body is due to medium length proteins, the unfermentable complex sugars will lend some of the same feel.
For example, Laaglander’s DME from the Netherlands is a high quality extract that often has a finishing gravity (FG) as high as 1.020 from a common 1.040 OG. The heavier body is nice to have in a stout for example; all-grain brewers would add a dextrin malt (e.g. Briess Carapils) to their mash to produce the same effect. Brewers using extract have the alternative of adding malto-dextrin powder, which is a concentrated form. Malto-dextrin powder has no taste, i.e. it’s not sweet, and is slow to dissolve. It contributes about 40 points per pound per gallon.

To summarize—malt extract is not some mysterious substance but simply a concentrated wort, ready for brewing. You don’t need to agonize over which kit to buy, comparing labels and product claims; you can plan your own beer and buy the type of extract that you want to use to make it. Malt extract makes brewing easier by taking the work out of producing the wort. This lets a new brewer focus on the fermentation processes.
The next step in improving your brews and your control over recipes will be to get some of your flavor and color from specialty grains instead of just relying on whatever’s in the malt extract.  You will probably want to try it for your second or third batch, but it is certainly not difficult and could be done for a first beer. In Section II—Brewing With Extract and Specialty Grain, we will examine this middle ground, which offers the benefits of grain brewing without an investment in a lot of new equipment. 
Eventually, it will be useful to learn how to extract the sugars from the malted grain yourself. This process, called mashing, allows the brewer more control in producing the wort and tailoring the fermentability. This type of homebrewing is referred to as all-grain brewing, because the wort is produced from the grain without using any malt extract, and it is discussed in Section III—Brewing With All-Grain.

`;
