export default `

This is a crash course in boiling and cooling

Some Thoughts on Boil Gravity
Homebrewers have been using malt extract the same way for the last 30 years, if not longer. The standard extract brewing procedure has been to boil all of the extract at a high gravity, and dilute that wort in the fermentor. The benefits of this technique were sanitization of all the extract, and a very thorough hot break (coagulation) of any remaining protein from the extract manufacturing process. The issues with high gravity boils are: reduced hop isomerization, poorer foam stability, and flavor changes from Maillard reactions. Reduced hop isomerization is well known at high gravities but probably not economically significant for homebrewers. Poorer foam stability may come as a surprise, but it is a result of the greater concentration of protein in a high gravity wort causing a more efficacious coagulation and removal of foam-positive proteins from the wort. After dilution in the fermentor, there is less protein per volume to sustain the foam. Finally, many brewers talk about generating more complex malt flavors due to caramelization of wort sugars during high gravity boils. The flavor changes are real but they are actually due to Maillard reactions, not caramelization. True caramelization requires that the sugars be highly concentrated with little water, and temperatures in excess of 300°F (150°C). Maillard reactions occur at a wide range of temperature between a sugar and an amino acid, and the flavor produced depends on the temperature and the specific amino acid involved.

In Chapter 3, I mentioned a group of off-flavors known as extract twang. Some of these flavors are due to oxidation of fatty acids (i.e., staling), but others are due to Maillard reactions and can include molasses, licorice, and phenolic odors like ink. The potential flavor changes depend on many factors, and I am not saying that high gravity boils always produce inky-tasting beers. In dark beers the Maillard flavors may readily blend with the malt flavors, but in lighter beers, the flavors may stick out like a sore thumb. It will depend on the wort composition and on the conditions at the time. Maillard reactions also cause wort darkening, which can be frustrating for an extract brewer trying to brew a Munich Helles or Pilsener to style. One partial solution to all these issues is to reduce the gravity of the boil by saving some of the extract until the end of the boil. This last extract can be boiled for just a few minutes for pasteurization and then cooled and diluted in the fermentor as before. The result is less wort darkening, better foam stability and a reduction of potential off-flavors. I have made very good extract beers with this Late Extract method.
First Beer using Late Extract Method
For your first beer, let’s make an American pale ale. American pale ale is an adaptation of the classic British pale ale. With the resurgence of interest in ales in the United States, pale ale evolved to reflect a renewed interest in American hop varieties and a higher level of bitterness as microbreweries experimented with craft brewing. 

American pale ale has a cleaner, less fruity taste than its British counterparts because American ale yeast strains are less fruity than comparable English ale yeast. Pale ales vary in color from gold to dark amber and typically have a hint of sweet caramel (from the use of caramel malts) that does not mask the hop finish. We will use amber malt extract for part of our recipe, which contains caramel malt, to achieve this. 

The Cascade hop has become a staple of American microbrewing. It has a distinct citrus aroma compared to the European hops and has helped American pale ale stand shoulder to shoulder with other classic beer styles of the world. Prime examples of this style are Anchor Liberty Ale and Sierra Nevada Pale Ale. The finishing hops are usually Cascade, though other American hop varieties like Amarillo, Liberty, or Willamette work as well. American pale ale is also commonly dry hopped. For more hop aroma, an additional half-ounce can be added to the primary fermentor after the bubbling starts to taper off. Dry hopping does not increase the bitterness of the ale, but it adds a wonderful aroma and some flavor.
Beginning the Boil
[figure 48 – pot on stove with ingredients laid out]

1. Prepare the brew water. In the brewpot, bring about 3 gallons of water to a boil. Pour this water into the bucket fermentor and leave it to cool. Actually, it helps to do this step the night before. (Don’t pour hot water into a glass carboy.) 
Note: If your tap water is clean and fresh tasting, you probably don’t need to boil it before adding it to the fermentor. But if you have any doubts, boil it to be sure.
[figure 49 – Steeping specialty grains.]
2. Add malt extract. Dissolve the 2.5 pounds of dry malt extract into 3 gallons of cold water in the brewpot. You will be boiling the hops in this wort. Some water will evaporate during the boil, and some will be lost to the trub. Starting out with six gallons total between the brewpot and the fermentor will help ensure that you hit your five gallon recipe volume. 
If your recipe has specialty grains, you should steep them in hot water, just as if you were making a cup of tea. The water should be hot but not boiling. Try to aim for 150-170°F, the same general range as for mashing. After the specialty grain has steeped for a half hour. Remove the bag and allow it to drain. Then you can begin boiling your wort.
3. Boil it Bring the wort to a boil, stirring regularly to be sure that it doesn’t scorch. See Figure 50.
The Hot Break
 4. Watch the pot for boilovers 
This next stage is critical. The pot needs to be watched constantly. As the wort boils, a foam will start to rise and form a smooth surface. This is good. If the foam suddenly billows over the side, this is a boil-over (bad). If it looks like it is going to boil over, either lower the heat or spray the surface with water from a spray bottle. Putting a few copper pennies into the pot to act as boil initiators will also help prevent boilovers. 

The foam is caused by the coagulation of proteins in the wort during the boil. The wort will continue to foam until the protein clumps get heavy enough to sink back into the pot. You will see particles floating around in the wort. It may look like Egg Drop Soup. This is called the hot break, and may take 5-20 minutes to occur, depending on the amount of protein in your extract. The extract has already been boiled once when it was made, so usually there is not very much at this stage. Often the first hop addition triggers a great deal of foaming, especially if hop pellets are used. I recommend waiting until the hot break occurs before doing your first hop addition and timing the hour. The extra boiling time won’t hurt.

[fig 51 – foaming boil]
Covering the pot with the lid can help with heat retention and help you achieve your boil, but it can also lead to trouble. Murphy’s Law has its own brewing corollary: “If it can boil over, it will boil over.”  Covering the pot and turning your back on it is the quickest way to achieve a boilover. If you cover the pot, watch it like a hawk...a hawk and ten buzzards even.

Once you achieve a boil, only partially cover the pot, if at all. Why?  Because in wort there are sulfur compounds that evolve and boil off. If they aren’t removed during the boil, they will later form dimethyl sulfide which contributes a cooked cabbage or corn-like flavor to the beer. If the cover is left on the pot, or left on such that the condensate from the lid can drip back in, then these flavors will have a much greater chance of showing up in the beer.
Hop Additions
[figure 52 – hop addition]
5. Add hops (T = 60 minutes). Once the hot break has occurred, add all of the bittering hops. Stir them in so that they are all wetted. Be careful that the wort doesn’t boil over when you add them. These should be boiled for about an hour to isomerize the alpha acids for bittering. See Chapter 5 for details on how the hop additions affect the beer’s flavor.
[figure 53 – another hop addition]
6. Add more hops (T= 30 minutes). Continue the rolling boil for the remainder of the hour. Stir occasionally to prevent scorching. There will probably be a change in color and aroma and there will be clumps of stuff floating in the wort. This is not a concern, it’s the hot break material i.e. coagulated/precipitated protein. Add half of the finishing hops at 30 minutes before the end of the boil. 
7. Add more hops (T = 15 minutes). Add the last half of the finishing hops at 15 minutes before the end of the boil. These late additions allow less time for the volatile oils to boil away, increasing hop flavor and aroma. You can add a little more at knockout (after the heat is off and the wort is starting to cool) if still more hop aroma is desired. Refer to Chapter 5—Hops for more information.
8. Add the rest of the extract (T = 5 minutes). Okay, you are almost done brewing. It is time to add the rest of your malt extract (the pale liquid malt extract) to the boil to pasteurize it before we cool the wort and dilute it in the fermentor. 
Cooling the Wort
[figure 54 – pot cooling in ice bath]
At the end of the boil, it is better to cool the wort quickly for several reasons. If the wort is cooled slowly, the dimethyl sulfide pre-cursors will continue to be produced in the hot wort. Without the boil to drive them off, DMS off-flavors will be generated in the beer. The objective is to rapidly cool the wort to below 80°F before oxidation or contamination can occur. For your first batch, I recommend using a cold water bath to chill the wort, but alternative methods are presented on the next page.
Rapid cooling also helps form the “cold break.” This is composed of another group of proteins that precipitate out of the wort. Cold break, or rather the lack of it, is the cause of “chill haze.” When a beer is chilled for drinking, these proteins partially precipitate forming a haze. As the beer warms up, the proteins re-dissolve. Rapid chilling from near-boiling to room temperature will help more of the cold break proteins permanently precipitate and not cause chill haze.  Chill haze is usually regarded as a cosmetic problem; you cannot taste it. However, chill haze indicates that there is an appreciable level of cold-break-type protein in the beer, which has been linked to long-term stability problems. Hazy beer tends to become stale sooner than non-hazy beer. 
Water Bath
9. Cool It 
Place the pot in a sink or tub filled with cold/ice water that can be circulated around the hot pot. As mentioned in the previous chapter, it is best to keep the pot lid on, but if you are careful you can speed up the cooling by stirring. Gently stir the wort in a circular manner so the maximum amount of wort is moving against the sides of the pot. Minimize splashing to avoid oxidation. Don’t let water from your hands drip inside the pot; this could be a source of contamination. If the cooling water gets warm, replace with colder water. The wort should cool to 70°F (21°C) in about 30 minutes. The closer you can get it to your fermentation temperature, the better. 
10. Ferment the Wort 
See the next chapter for a thorough discussion of what fermentation is, and chapter 9 following for the rest of the instructions for fermenting your first batch.
Ice
People often wonder about adding ice directly to the cooling wort. This idea works well if you remember a couple key points. 
•	Always boil the water before freezing it in an airtight container (like Tupperware). It must be airtight because most freezers also harbor dormant bacteria. 
•	Never use commercial ice. If the water or facility was not clean, it can harbor dormant bacteria that could spoil your beer.
•	If the ice will not directly contact the wort, (i.e. you are using a frozen plastic soda bottle or other container in the wort) make sure you sanitize the outside of the bottle first before you put it in the wort. 
Copper Wort Chillers
[figure 55 – immersion chiller in pot]
A wort chiller is a coil of copper tubing that is used as a heat exchanger to cool the wort in-place. Wort chillers are not necessary for your first batch of beer, when you are only boiling 2-3 gallons, but this is a good time to make you aware of them. Wort chillers are useful for cooling full volume boils because you can leave the wort on the stove instead of carrying it to a sink or bathtub. Five gallons of boiling hot wort weighs almost 45 pounds and is hazardous to carry.

There are two basic types of wort chillers: immersion and counter-flow. Immersion chillers are the simplest and work by running cold water through the coil. The chiller is immersed in the wort and the water carries the heat away. Counterflow chillers work in an opposite manner. The hot wort is drained from the pot through the copper tubing while cold water flows around the outside of the chiller. Immersion chillers are often sold in homebrew supply shops or can be easily made at home. Instructions for building both types of chiller are given in Appendix C.
Murphy's Laws of Brewing
If it can boil over, it will boilover.
Nature always hides in the hidden flaw.
If you keep messing with it, you will probably screw it up.
If you don’t have time to do it right, you will probably end up doing it over.
The race is not always to the swift, nor the battle to the strong, but that’s the way to bet. 
(i.e., The most conscientious brewer may not win all the ribbons, but he will probably win most of them.)

Did you ever wonder where Murphy’s Law came from? Well back at work there was a photocopy of a short article from one of the aerospace trade journals on the wall of my friend’s cubicle. It went something like this:

Captain Murphy was part of an engineering team out at Edward’s Air Force Base in California. Their team was investigating the effects of high gravity de-accelerations on jet pilots back in the 1950’s. One of their tests involved strapping a test pilot into a rocket chair equipped with strain gages and other sensors to help them quantify the effects of high G stopping. The responsibility for the placement of the various sensors was Capt. Murphy’s. Well, the test was run (subjecting the pilot to something like 100 G’s of deceleration) and he got pretty banged up.
Only after it was over did the team realize that of all the possible combinations of placing those sensors, Murphy had done it in the one configuration that resulted in useless data. They would have to run the test again. Upon realizing this, Murphy stated, “If there are two or more ways of doing something, and one of them can result in catastrophe, someone will do it that way.”  Upon hearing this the team leader said, “That’s Murphy’s Law.”  The next day at the test de-briefing the team leader shortened it to the now famous, “If anything can go wrong, it will.”
Murphy still likes his version better.

Working with Malt Extract
Dry malt extract is easiest to dissolve in cold water. In hot water it tends to clump and takes a lot of stirring to dissolve the clumps. On the other hand, liquid malt extract is easier to dissolve in hot water. It will also pour easier if you warm the can beforehand and use a spatula to get every drop. It is a good idea to turn the heat off while you are dissolving liquid extract so that it doesn’t sit of the bottom of the pot and scorch.

`;
