"use client";

import { useState } from "react";
import BrewCompanionModal from "../components/BrewCompanionModal";

export default function RecipeBuilder() {
  const [recipeId, setRecipeId] = useState<string | null>(null);

  const [name, setName] = useState("");
  const [ingredients, setIngredients] = useState("");
  const [method, setMethod] = useState("");
  const [notes, setNotes] = useState("");
  const [style, setStyle] = useState("standard");
  const [volume, setVolume] = useState(""); // ⭐ NEW
  const [statusMsg, setStatusMsg] = useState("");

  const [showModal, setShowModal] = useState(false);

  // Robust parsing of AI draft
  function extractSection(text: string, section: string) {
    if (!text) return ""; // <-- FIX 1
    const regex = new RegExp(
      `${section}\\s*:?\\s*([\\s\\S]*?)(?=\\n\\s*[A-Z][a-z]+\\s*:|$)`,
      "i"
    );
    const match = text.match(regex);
    return match ? match[1].trim() : "";
  }

  // When BrewCompanion finishes → fill in the draft
  function handleBrewCompanionFinish(
    draftText: string,
    meta?: { name: string; style: string; volume: string } // ⭐ NEW
  ) {
    if (!draftText || typeof draftText !== "string") { // <-- FIX 2
      setStatusMsg("AI returned an empty draft.");
      return;
    }

    // Fill in name and style from BrewCompanionModal
    if (meta?.name) setName(meta.name);
    if (meta?.style) setStyle(meta.style);
    if (meta?.volume) setVolume(meta.volume); // ⭐ NEW

    // Fill in sections from AI draft
    setIngredients(extractSection(draftText, "Ingredients"));
    setMethod(extractSection(draftText, "Method"));

    // Notes should be empty
    setNotes("");

    setStatusMsg("Draft generated by BrewCompanion!");
  }

  /* -----------------------------------------
     SAVE NEW RECIPE (POST)
  ----------------------------------------- */
  async function saveRecipe() {
    const res = await fetch("/api/recipes", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        name,
        ingredients,
        method,
        notes,
        volume, // ⭐ NEW
      }),
    });

    if (res.ok) {
      const data = await res.json();
      setRecipeId(data.recipe.id); // now you can update later
      setStatusMsg("Recipe saved!");
    } else {
      setStatusMsg("Could not save recipe.");
    }
  }

  /* -----------------------------------------
     UPDATE EXISTING RECIPE (PATCH)
  ----------------------------------------- */
  async function updateRecipe() {
    if (!recipeId) {
      setStatusMsg("No recipe to update.");
      return;
    }

    const res = await fetch(`/api/recipes/${recipeId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        name,
        ingredients,
        method,
        notes,
        volume, // ⭐ NEW
      }),
    });

    if (res.ok) {
      setStatusMsg("Recipe updated!");
    } else {
      setStatusMsg("Could not update recipe.");
    }
  }
  return (
    <main className="min-h-screen px-6 py-12 text-white flex justify-center">
      <div className="bg-black/60 backdrop-blur-md p-8 rounded-xl w-full max-w-3xl border border-white/10">

        <h1 className="text-4xl font-bold mb-6 text-center">
          Recipe Builder
        </h1>

        <div className="flex flex-col gap-6">

          <div>
            <label className="block mb-1 font-semibold">Recipe Name</label>
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="E.g. Mango Mead"
              className="w-full p-3 rounded bg-black/40 border border-white/20"
            />
          </div>

          <div>
            <label className="block mb-1 font-semibold">Style</label>
            <input
              value={style}
              onChange={(e) => setStyle(e.target.value)}
              placeholder="E.g. tropical, sour, standard, strong..."
              className="w-full p-3 rounded bg-black/40 border border-white/20"
            />
          </div>

          <div>
            <label className="block mb-1 font-semibold">Ingredients</label>
            <textarea
              value={ingredients}
              onChange={(e) => setIngredients(e.target.value)}
              placeholder="Write the ingredients here..."
              className="w-full p-3 rounded bg-black/40 border border-white/20 h-32"
            />
          </div>

          <div>
            <label className="block mb-1 font-semibold">Method</label>
            <textarea
              value={method}
              onChange={(e) => setMethod(e.target.value)}
              placeholder="Write the method here..."
              className="w-full p-3 rounded bg-black/40 border border-white/20 h-32"
            />
          </div>

          <div>
            <label className="block mb-1 font-semibold">Notes</label>
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Notes, tips, variations..."
              className="w-full p-3 rounded bg-black/40 border border-white/20 h-24"
            />
          </div>

          {/* Buttons change automatically */}
          {recipeId ? (
            <button
              onClick={updateRecipe}
              className="px-4 py-3 bg-yellow-600 hover:bg-yellow-500 border border-yellow-400 rounded-lg font-semibold"
            >
              Update Recipe
            </button>
          ) : (
            <button
              onClick={saveRecipe}
              className="px-4 py-3 bg-green-700 hover:bg-green-600 border border-green-500 rounded-lg font-semibold"
            >
              Save Recipe
            </button>
          )}

          <button
            onClick={() => setShowModal(true)}
            className="px-4 py-3 bg-blue-700 hover:bg-blue-600 border border-blue-500 rounded-lg font-semibold"
          >
            Generate Recipe
          </button>

          {statusMsg && (
            <p className="text-center opacity-80 mt-4">{statusMsg}</p>
          )}
        </div>
      </div>

      {/* BrewCompanion Modal */}
      <BrewCompanionModal
        isOpen={showModal}
        onClose={() => setShowModal(false)}
        onFinish={handleBrewCompanionFinish}
      />
    </main>
  );
}
