"use client";

import { useState } from "react";
import BrewCompanionModal from "../components/BrewCompanionModal";
import UniversalMenuOverlay from "@/app/components/MenuOverlay";
import BackButton from "./BackButton";

export default function RecipeBuilder() {
  const [recipeId, setRecipeId] = useState<string | null>(null);

  const [name, setName] = useState("");
  const [ingredients, setIngredients] = useState("");
  const [method, setMethod] = useState("");
  const [notes, setNotes] = useState("");
  const [style, setStyle] = useState("standard");
  const [volume, setVolume] = useState("");
  const [statusMsg, setStatusMsg] = useState("");

  const [showModal, setShowModal] = useState(false);

  function extractSection(text: string, section: string) {
    if (!text) return "";
    const regex = new RegExp(
      `${section}\\s*:?\\s*([\\s\\S]*?)(?=\\n\\s*[A-Z][a-z]+\\s*:|$)`,
      "i"
    );
    const match = text.match(regex);
    return match ? match[1].trim() : "";
  }

  function handleBrewCompanionFinish(
    draftText: string,
    meta?: { name: string; style: string; volume: string }
  ) {
    if (!draftText || typeof draftText !== "string") {
      setStatusMsg("AI returned an empty draft.");
      return;
    }

    if (meta?.name) setName(meta.name);
    if (meta?.style) setStyle(meta.style);
    if (meta?.volume) setVolume(meta.volume);

    setIngredients(extractSection(draftText, "Ingredients"));
    setMethod(extractSection(draftText, "Method"));
    setNotes("");

    setStatusMsg("Draft generated by BrewCompanion!");
  }

  async function saveRecipe() {
    const res = await fetch("/api/recipes", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "include", // ⭐ VIKTIG
      body: JSON.stringify({
        name,
        ingredients,
        method,
        notes,
        volume,
      }),
    });

    if (res.ok) {
      const data = await res.json();
      setRecipeId(data.recipe.id);
      setStatusMsg("Recipe saved!");
    } else {
      setStatusMsg("Could not save recipe.");
    }
  }

  async function updateRecipe() {
    if (!recipeId) {
      setStatusMsg("No recipe to update.");
      return;
    }

    const res = await fetch(`/api/recipes/${recipeId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      credentials: "include", // ⭐ VIKTIG
      body: JSON.stringify({
        name,
        ingredients,
        method,
        notes,
        volume,
      }),
    });

    if (res.ok) {
      setStatusMsg("Recipe updated!");
    } else {
      setStatusMsg("Could not update recipe.");
    }
  }

  return (
    <main className="min-h-screen px-6 py-12 text-white flex justify-center">
      <div className="bg-black/60 backdrop-blur-md p-8 rounded-xl w-full max-w-3xl border border-white/10 relative">

        {/* TOP BAR */}
        <div className="flex items-center justify-between mb-6 h-10">
          <BackButton />
          <UniversalMenuOverlay current="companion" />
        </div>

        <h1 className="text-4xl font-bold mb-6 text-center">
          BrewCompanion (Work in progress)
        </h1>
        <p className="opacity-80 text-center mb-10">
          AI BrewCompanion. Press "Generate Recipe" to start.
        </p>

        <div className="flex flex-col gap-6">

          <div>
            <label className="block mb-1 font-semibold">Recipe Name</label>
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="E.g. Mango Mead"
              className="w-full p-3 rounded bg-black/40 border border-white/20"
            />
          </div>

          <div>
            <label className="block mb-1 font-semibold">Style</label>
            <input
              value={style}
              onChange={(e) => setStyle(e.target.value)}
              placeholder="E.g. tropical, sour, standard, strong..."
              className="w-full p-3 rounded bg-black/40 border border-white/20"
            />
          </div>

          <div>
            <label className="block mb-1 font-semibold">Ingredients</label>
            <textarea
              value={ingredients}
              onChange={(e) => setIngredients(e.target.value)}
              placeholder="Write the ingredients here..."
              className="w-full p-3 rounded bg-black/40 border border-white/20 h-32"
            />
          </div>

          <div>
            <label className="block mb-1 font-semibold">Method</label>
            <textarea
              value={method}
              onChange={(e) => setMethod(e.target.value)}
              placeholder="Write the method here..."
              className="w-full p-3 rounded bg-black/40 border border-white/20 h-32"
            />
          </div>

          <div>
            <label className="block mb-1 font-semibold">Notes</label>
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Notes, tips, variations..."
              className="w-full p-3 rounded bg-black/40 border border-white/20 h-24"
            />
          </div>

          {recipeId ? (
            <button
              onClick={updateRecipe}
              className="px-4 py-3 bg-yellow-600 hover:bg-yellow-500 border border-yellow-400 rounded-lg font-semibold"
            >
              Update Recipe
            </button>
          ) : (
            <button
              onClick={saveRecipe}
              className="px-4 py-3 bg-green-700 hover:bg-green-600 border border-green-500 rounded-lg font-semibold"
            >
              Save Recipe
            </button>
          )}

          <button
            onClick={() => setShowModal(true)}
            className="px-4 py-3 bg-blue-700 hover:bg-blue-600 border border-blue-500 rounded-lg font-semibold"
          >
            Generate Recipe
          </button>

          {statusMsg && (
            <p className="text-center opacity-80 mt-4">{statusMsg}</p>
          )}
        </div>

        <p className="text-sm opacity-40 mt-12 text-center">
          © {new Date().getFullYear()} Batchlog
        </p>
      </div>

      <BrewCompanionModal
        isOpen={showModal}
        onClose={() => setShowModal(false)}
        onFinish={handleBrewCompanionFinish}
      />
    </main>
  );
}
